"""1.3.0

Revision ID: af9b409bcc5e
Revises: a19a48dbb41b
Create Date: 2024-05-06 09:50:44.753864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9b409bcc5e'
down_revision = 'a19a48dbb41b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONFIG_SITE', sa.Column('APIKEY', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CONFIG_SITE', 'APIKEY')
    # ### end Alembic commands ###
